config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }

  scope module: :users, path: 'users' do
    resource :registration, only: [:show, :update]
    resource :change_passwords, only: [:edit, :update]
  end

  scope module: :classrooms, path: 'classrooms' do
    resource  :join,       only: [:create, :destroy]
    resources :my_classes, only: :index
  end

  resources :profiles,    only: [:index]
  resources :skills,      only: [:create, :destroy]
  resource  :users,       only: [:edit, :update]
  resources :users,       only: [:index, :show]
  resources :friendships, only: [:create, :destroy, :update]
  resources :posts,       only: [:new, :create, :edit, :update, :destroy, :show]
  resources :likes,       only: [:create]
  resources :comments,    only: [:create]

  resources :classrooms, only: [:index, :new, :create, :show, :edit, :update] do
    scope module: :classrooms do
      resources :posts, only: [:new, :create, :edit, :update, :destroy, :show]
    end
  end

  root to: 'home#index'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @already_know_skills       = user_skills[:already_know]
    @currently_learning_skills = user_skills[:currently_learning]
    @want_to_learn_skills      = user_skills[:want_to_learn]

    @posts = current_user.posts.includes(:comments).where(classroom_id: nil).order(id: :desc)
    @renderer = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    @user_like_ids = current_user.likes.pluck(:post_id)

    @comments = Hash.new
    @posts.each do |post|
      @comments[post.id] = post.comments.collect do |comment|
        {
          body: comment.body,
          user: comment.user
        }
      end
    end
  end
end

app/views/profiles/index.slim
.profile-index
  .row
    h1.ml-3.float-left= "My Profile #{link_to icon('fas', 'cog'), edit_users_path}".html_safe
  hr
  .card
    .card-body
      h4.card-title What I already know
      = react_component 'Skills', { kind_of: 'already_know', skills: @already_know_skills }
  .card
    .card-body
      h4.card-title What I want to learn
      = react_component 'Skills', { kind_of: 'want_to_learn', skills: @want_to_learn_skills }
  .card
    .card-body
      h4.card-title What I am currently learning
      = react_component 'Skills', { kind_of: 'currently_learning', skills: @currently_learning_skills }
  hr
  = render partial: 'shared/posts_comments', locals: { posts: @posts }