config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }

  scope module: :users, path: 'users' do
    resource :registration, only: [:show, :update]
    resource :change_passwords, only: [:edit, :update]
  end

  scope module: :classrooms, path: 'classrooms' do
    resource  :join,       only: [:create, :destroy]
    resources :my_classes, only: :index
  end

  resources :profiles,    only: [:index]
  resources :skills,      only: [:create, :destroy]
  resource  :users,       only: [:edit, :update]
  resources :users,       only: [:index, :show]
  resources :friendships, only: [:create, :destroy, :update]
  resources :posts,       only: [:new, :create, :edit, :update, :destroy, :show]
  resources :likes,       only: [:create]
  resources :comments,    only: [:create]

  resources :classrooms, only: [:index, :new, :create, :show, :edit, :update] do
    scope module: :classrooms do
      resources :posts, only: [:new, :create, :edit, :update, :destroy, :show]
    end
  end

  root to: 'home#index'
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :user

  has_many :user_classrooms
  has_many :users, through: :user_classrooms
  has_many :posts

  validates_presence_of :name
  validates_presence_of :description
  validates :group_id, uniqueness: true, presence: true, format: { with: /[\w \.\-@]+/, message: 'should be alphanumeric' }

  def to_param
    group_id
  end
end

app/controllers/classrooms/joins_controller.rb
class Classrooms::JoinsController < ApplicationController
  def create
    @classroom = Classroom.find(params[:id])
    current_user.classrooms << @classroom
    redirect_to my_classes_path, notice: "Class #{@classroom.name} joined !!"
  end

  def destroy
    classroom = Classroom.find(params[:id])

    if UserClassroom.find_by_classroom_id(classroom.id).try(:destroy)
      redirect_to my_classes_path, alert: "Left class #{classroom.name}"
    end
  end
end

app/controllers/classrooms/my_classes_controller.rb
class Classrooms::MyClassesController < ApplicationController
  def index
    @q = current_user.classrooms.ransack(params[:q])
    @classrooms = @q.result
  end
end

app/controllers/classrooms/posts_controller.rb
class Classrooms::PostsController < ApplicationController
  before_action :set_classroom
  prepend_before_action :clear_notifications, only: :show

  def new
    @post = @classroom.posts.new
  end

  def edit
    @post = @classroom.posts.find(params[:id])
  end

  def show
    redirect_to classrooms_path, notice: "Please join #{@classroom.name} first." unless show_class?

    @user_like_ids = current_user.likes.pluck(:post_id)
    @post = @classroom.posts.find(params[:id])
    @comments = Hash.new
    @renderer = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    @comments[@post.id] = @post.comments.collect do |comment|
      {
        body: comment.body,
        user: comment.user
      }
    end
  end

  def create
    @post = @classroom.posts.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to classroom_path(@classroom), notice: 'Post created !!'
    end
  end

  def update
    @post = @classroom.posts.find(params[:id])

    if @post.update(post_params)
      redirect_to classroom_post_path(@post, classroom_id: @classroom.id), notice: 'Post updated !!'
    end
  end

  def destroy
    @post = @classroom.posts.find(params[:id])

    if @post.destroy
      redirect_to classroom_path(@classroom), alert: 'Post deleted !!'
    end
  end

  private

  def set_classroom
    @classroom = Classroom.find(params[:classroom_id])
  end

  def post_params
    params.require(:post).permit(:body)
  end

  def clear_notifications
    Notification.where(
      user_id: current_user.id,
      connected_id: "post:#{params[:id]}",
      is_read: false
    ).update_all(is_read: true)
  end

  def show_class?
    current_user.has_class?(@classroom) || @classroom.public?
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  def index
    classes_already_joined_ids = current_user.classrooms.pluck(:id)
    @q = Classroom.where.not(id: classes_already_joined_ids).ransack(params[:q])
    @classrooms = @q.result
  end

  def new
    @classroom = Classroom.new
  end

  def edit
    @classroom = Classroom.find_by_group_id(params[:id])

    if @classroom.user != current_user
      redirect_to classroom_path(@classroom), alert: 'You do not have permission for this action.'
      return
    end
  end

  def update
    @classroom = Classroom.find_by_group_id(params[:id])

    if @classroom.user != current_user
      redirect_to classroom_path(@classroom), alert: 'You do not have permission for this action.'
      return
    end

    if @classroom.update(classroom_params)
      redirect_to classroom_path(@classroom), notice: 'Classroom has been updated !!'
    else
      render :edit
    end
  end

  def show
    @classroom = Classroom.find_by_group_id(params[:id])
    redirect_to classrooms_path, notice: "Please join #{@classroom.name} first." unless show_class?

    @posts = @classroom.posts.order(id: :desc)
    @user_like_ids = current_user.likes.pluck(:post_id)
    @renderer = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    @comments = Hash.new

    @posts.each do |post|
      @comments[post.id] = post.comments.collect do |comment|
        {
          body: comment.body,
          user: comment.user
        }
      end
    end
  end

  def create
    @classroom = Classroom.new(classroom_params)
    @classroom.user = current_user

    if @classroom.save
      current_user.classrooms << @classroom
      redirect_to my_classes_path, notice: 'Class created !!'
    else
      render :new
    end
  end

  private

  def classroom_params
    params.require(:classroom).permit(:name, :description, :looking_for, :public, :group_id)
  end

  def show_class?
    current_user.has_class?(@classroom) || @classroom.public?
  end
end

app/views/classrooms/edit.slim
h1 Edit Classroom
hr
= simple_form_for @classroom, url: classroom_path(@classroom), method: :put do |f|
  = f.input :name
  = f.input :description
  = f.input :group_id, label: 'Group ID (Alphanumeric only)'
  = f.input :looking_for, label: 'Looking for (Enter words separated by a space. Eg. mentors learners equipments)', placeholder: 'Enter words separated by a space. (Eg. mentors learners equipments)'
  = f.input :public, label: 'Show class to non-members?'
  = f.submit 'Save', class: 'btn btn-success'

app/views/classrooms/index.slim
.classrooms-index
  h3 Find a class
  hr

  = search_form_for @q do |f|
    = f.search_field :name_or_description_or_looking_for_cont, class: 'form-control', placeholder: 'Search a class'

  br

  - if @classrooms.count.zero?
    h6.text-center= "No classes available. #{link_to 'Create one', new_classroom_path}".html_safe
  - else
    - @classrooms.each do |classroom|
      .card.mb-4
        .card-body
          h5.card-title= "#{link_to classroom.name, classroom_path(classroom)} #{icon('fas', 'lock') unless classroom.public?}".html_safe
          h6.card-subtitle.text-muted= "Created #{time_ago_in_words classroom.created_at} ago by #{classroom.user.name}"
          hr
          p.card-text= classroom.description
          p.card-text We are looking for:
          - classroom.looking_for.split(' ').each do |looking|
            span.badge.badge-light= looking
          br
          br
          = link_to icon('fas', 'check', ' Join Class'), join_path(id: classroom.id), class: 'btn btn-success float-right', method: :post

app/views/classrooms/new.slim
h3 Create a class
hr

= simple_form_for @classroom do |f|
  = f.input :name
  = f.input :description
  = f.input :group_id, label: 'Group ID (Alphanumeric only)'
  = f.input :looking_for, placeholder: 'Enter words separated by a space. (Eg. mentors learners equipments)'
  = f.submit 'Create class', class: 'btn btn-primary'
  = button_tag 'Clear', class: 'btn btn-link', type: :reset

app/views/classrooms/show.slim
h3= "#{link_to @classroom.name, classroom_path(@classroom)} #{link_to(icon('fas', 'cog'), edit_classroom_path(@classroom)) if @classroom.user == current_user}".html_safe
hr

- if current_user.has_class?(@classroom)
  = link_to 'Create a post', new_classroom_post_path(classroom_id: @classroom.id), class: 'btn btn-secondary btn-lg btn-block'
.mb-4

- if @posts.count.zero?
  .text-center No posts to show
- else
  - @posts.each do |post|
    .home-index
      .card
        .card-body
          span.card-title= link_to post.user.name, user_path(post.user)
          br
          = link_to classroom_post_path(post, classroom_id: @classroom.id) do
            small.card-subtitle.text-muted
              = "Posted #{time_ago_in_words post.created_at} ago"
          - if post.user == current_user
            hr
            = link_to icon('fas', 'edit', ' Edit'), edit_classroom_post_path(post, classroom_id: @classroom.id), class: 'btn btn-warning btn-sm'
            = link_to icon('fas', 'trash', ' Delete'), classroom_post_path(post, classroom_id: @classroom.id), class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' }
          hr
          = @renderer.render(post.body).html_safe
          hr
          = react_component 'LikesComments', { post_id: post.id, like_count: post.likes.count, liked: @user_like_ids.include?(post.id), comments: @comments[post.id], disabled: !current_user.has_class?(@classroom) }