config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }

  scope module: :users, path: 'users' do
    resource :registration, only: [:show, :update]
    resource :change_passwords, only: [:edit, :update]
  end

  scope module: :classrooms, path: 'classrooms' do
    resource  :join,       only: [:create, :destroy]
    resources :my_classes, only: :index
  end

  resources :profiles,    only: [:index]
  resources :skills,      only: [:create, :destroy]
  resource  :users,       only: [:edit, :update]
  resources :users,       only: [:index, :show]
  resources :friendships, only: [:create, :destroy, :update]
  resources :posts,       only: [:new, :create, :edit, :update, :destroy, :show]
  resources :likes,       only: [:create]
  resources :comments,    only: [:create]

  resources :classrooms, only: [:index, :new, :create, :show, :edit, :update] do
    scope module: :classrooms do
      resources :posts, only: [:new, :create, :edit, :update, :destroy, :show]
    end
  end

  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.includes(:comments).where(classroom_id: nil).order(id: :desc)
    @user_like_ids = current_user.likes.pluck(:post_id)
    @renderer = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    @comments = Hash.new

    @posts.each do |post|
      @comments[post.id] = post.comments.collect do |comment|
        {
          body: comment.body,
          user: comment.user
        }
      end
    end
  end
end

app/views/home/index.slim
- if @posts.count.zero?
  .jumbotron
    h1.text-center Welcome to Haraya
    p.lead.text-center Something written in here I don't know what
    p.text-center
      = link_to 'Go to my profile', profiles_path
- else
  - @posts.each do |post|
    .home-index
      .card
        .card-body
          span.card-title= link_to post.user.name, user_path(post.user)
          br
          = link_to post_path(post) do 
            small.card-subtitle.text-muted
              = "Posted #{time_ago_in_words post.created_at} ago"
          - if post.user == current_user
            hr
            = link_to icon('fas', 'edit', ' Edit'), edit_post_path(post), class: 'btn btn-warning btn-sm'
            = link_to icon('fas', 'trash', ' Delete'), post_path(post), class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' }
          hr
          = @renderer.render(post.body).html_safe
          hr
          = react_component 'LikesComments', { post_id: post.id, like_count: post.likes.count, liked: @user_like_ids.include?(post.id), comments: @comments[post.id], disabled: false }