config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }

  scope module: :users, path: 'users' do
    resource :registration, only: [:show, :update]
    resource :change_passwords, only: [:edit, :update]
  end

  scope module: :classrooms, path: 'classrooms' do
    resource  :join,       only: [:create, :destroy]
    resources :my_classes, only: :index
  end

  resources :profiles,    only: [:index]
  resources :skills,      only: [:create, :destroy]
  resource  :users,       only: [:edit, :update]
  resources :users,       only: [:index, :show]
  resources :friendships, only: [:create, :destroy, :update]
  resources :posts,       only: [:new, :create, :edit, :update, :destroy, :show]
  resources :likes,       only: [:create]
  resources :comments,    only: [:create]

  resources :classrooms, only: [:index, :new, :create, :show, :edit, :update] do
    scope module: :classrooms do
      resources :posts, only: [:new, :create, :edit, :update, :destroy, :show]
    end
  end

  root to: 'home#index'
end

app/views/layouts/application.slim
doctype html
html
  head
    title Haraya
    = csrf_meta_tags
    = csp_meta_tag
    meta name='viewport' content='width=device-width, initial-scale=1.0'

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

    link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css"
    script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"
    script src='https://www.googletagmanager.com/gtag/js?id=UA-157806539-1'
    javascript:
      window.dataLayer = window.dataLayer || [];
      function gtag() { dataLayer.push(arguments); }
      gtag('js', new Date());
      gtag('config', 'UA-157806539-1');

  body
    .container
      nav.navbar.navbar-expand.navbar-dark.bg-primary style='margin-bottom: 20px;'
        = link_to 'Haraya', root_path, class: 'navbar-brand'
        ul.navbar-nav.mr-auto
          li.nav-item
            = link_to icon('fas', 'home'), root_path, class: 'nav-link'
        ul.navbar-nav
          li.nav-item style='display: inline-block; margin-right: 4px;'
            = link_to icon('fas', 'user-circle', " #{current_user.name}"), profiles_path, class: 'nav-link', data: { toggle: 'tooltip', placement: 'bottom', title: 'My Profile' }
          li.nav-item style='display: inline-block'
            = link_to icon('fas', 'plus'), new_post_path, class: 'nav-link', data: { toggle: 'tooltip', placement: 'bottom', title: 'Add a post' }
          li.nav-item style='display: inline-block'
            = link_to icon('fas', 'chalkboard-teacher'), new_classroom_path, class: 'nav-link', data: { toggle: 'tooltip', placement: 'bottom', title: 'Create a class' }
          li.nav-item style='display: inline-block'
            = link_to icon('fas', 'user-friends'), users_path, class: 'nav-link', data: { toggle: 'tooltip', placement: 'bottom', title: 'Find a friend' }
          li.nav-item.dropdown style='display: inline-block'
            - notif_count = current_user.unread_notifications.count
            - notif_count = '' if notif_count.zero?
            = link_to icon('fas', 'bell', " <span class='badge badge-pill badge-danger'>#{notif_count}</span>".html_safe), nil, class: 'nav-link', data: { toggle: 'dropdown' }
            .dropdown-menu.dropdown-menu-right aria-labelledby='navbarDropdownNotifications' style='padding: 0; width: 300px;'
              .list-group
                - if @notifications.count.zero? 
                  a.list-group-item.list-group-item-action
                    p.text-center.mt-3 No new notification
                - else
                  - @notifications.each do |notification|
                    a.list-group-item.list-group-item-action href="#{notification.link}"
                      = notification.message.html_safe
        ul.navbar-nav
          li.nav-item.dropdown
            a.nav-link.dropdown-toggle href='#' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'
            .dropdown-menu.dropdown-menu-right aria-labelledby='navbarDropdownMenuLink'
              = link_to icon('fas', 'search', ' Find Classes'), classrooms_path, class: 'dropdown-item'
              = link_to icon('fas', 'chalkboard', ' My Classes'), my_classes_path, class: 'dropdown-item'
              .dropdown-divider
              = link_to icon('fas', 'sign-out-alt', ' Sign Out'), destroy_user_session_path, method: :delete, class: 'dropdown-item'
      = render partial: 'shared/alerts'
      = yield

app/views/layouts/devise.slim
doctype html
html
  head
    title Haraya
    = csrf_meta_tags
    = csp_meta_tag
    meta name='viewport' content='width=device-width, initial-scale=1.0'

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

    script src='https://www.googletagmanager.com/gtag/js?id=UA-157806539-1'
    javascript:
      window.dataLayer = window.dataLayer || [];
      function gtag() { dataLayer.push(arguments); }
      gtag('js', new Date());
      gtag('config', 'UA-157806539-1');

  body
    = yield